app = "oversold-backend"
primary_region = "ord"

[build]
dockerfile = "Dockerfile"

[mounts]
source = "stocks_data"
destination = "/data"

[[services]]
internal_port = 8000
protocol = "tcp"
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
[[services.ports]]
port = 443
handlers = ["tls", "http"]