name: Update Database

on:
  schedule:
    - cron: '0 6 * * *'  # Runs at 6 AM UTC (1 AM CDT)

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger database update
      run: |
        curl -X POST https://oversold-backend.fly.dev/update-db
