name: Update Database

on:
  schedule:
    - cron: '30 20 * * *'  # Runs at 4:30PM Central

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger database update
      run: |
        curl -X POST https://oversold-backend.fly.dev/update-db
