# .github/workflows/update-db.yml
# This workflow runs daily to trigger the database update on Fly.io via curl.
# Since DB is on Fly volume, and memory issues on free tier, we keep the update on Fly for now.
# If memory persists, consider paid tier or local run with DB sync (complicated).
name: Update Database

on:
  schedule:
    - cron: '30 20 * * *'  # Runs at 4:30PM Central
  workflow_dispatch:  # Manual trigger

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger database update
        run: |
          curl -X POST https://oversold-backend.fly.dev/update-db
